when:
  - event: [push, tag, cron, manual]

steps:
  build84:
    image: coralhl/woodpecker-buildx-plugin
    privileged: true
    settings:
      repo: coralhl/alpine-nginx-php8
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      dockerfile: 84.Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
      tags:
      - latest
      - 8.4

  build83:
    image: coralhl/woodpecker-buildx-plugin
    privileged: true
    settings:
      repo: coralhl/alpine-nginx-php8
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      dockerfile: 83.Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
      tags:
      - 8.3

  build82:
    image: coralhl/woodpecker-buildx-plugin
    privileged: true
    settings:
      repo: coralhl/alpine-nginx-php8
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      dockerfile: 82.Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
      tags:
      - 8.2
