name: build and publish 8.4
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: alpine-nginx-php8
  IMAGE_TAG: "8.4 latest"
  IMAGE_PLATFORMS: linux/amd64,linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.IMAGE_PLATFORMS }}

      - name: Build Image
        id: build_image_multiplatform
        uses: coralhl/buildah-action@main
        with:
          dockerfile: '84.Dockerfile'
          image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }}
          platforms: ${{ env.IMAGE_PLATFORMS }}
          push: true
          registry: ${{ env.REGISTRY }}
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Copy from DH to REG 8.4
        uses: coralhl/skopeo-action@main
        with:
          source: docker://${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:8.4
          target: docker://${{ secrets.PRIV_REG }}/${{ secrets.PRIV_REG_USERNAME }}/${{ env.IMAGE_NAME }}:8.4
          source_username: ${{ secrets.DOCKERHUB_USERNAME }}
          source_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          target_username: ${{ secrets.PRIV_REG_USERNAME }}
          target_password: ${{ secrets.PRIV_REG_PASSWORD }}

      - name: Copy from DH to REG latest
        uses: coralhl/skopeo-action@main
        with:
          source: docker://${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          target: docker://${{ secrets.PRIV_REG }}/${{ secrets.PRIV_REG_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          source_username: ${{ secrets.DOCKERHUB_USERNAME }}
          source_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          target_username: ${{ secrets.PRIV_REG_USERNAME }}
          target_password: ${{ secrets.PRIV_REG_PASSWORD }}
